<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MyLib\**" />
    <Compile Remove="Buoi01Prj\**" />
    <Compile Remove="MyLib.Tests\**" />
    <Compile Remove="ThucHanh02\**" />
    <Compile Remove="ThucHanh02.Tests\**" />
  </ItemGroup>
</Project>
